### ISSUE TITLE
Length scale example showing different results (update needed)

### ISSUE THREAD

**Issue by franktoffel** [novonordisk-research/ProcessOptimizer#305] opened 2024-12-14 12:09 UTC
This example is no longer showing the same results.

https://github.com/novonordisk-research/ProcessOptimizer/blob/develop/examples/Length%20scale%20bounds.ipynb

The first plot returns this:
![620cd48e-5016-40f5-80e2-1929d204c14a](https://github.com/user-attachments/assets/327fc6c0-55e8-4305-8fd6-13cc4f003f9d)

The second:
![3b00a3af-5fb8-463d-87cd-6adb5e5b5b5f](https://github.com/user-attachments/assets/828801fe-ac21-43b2-967c-f812d4f4dc1e)

Some libraries are imported but never used as well. 

The commit was 5 years old, I expect it is an issue with changes in the version.

**Comment by sqbl** [comment] 2024-12-14 13:22
Dear Franktoffel,
Thank you very much for the information. This requires a bit of looking into. It would be wonderful if you can add a few more details: 
e.g. on the imported libraries that are unused (they might be used for other use-cases than vanilla Bayesian Optimization).

**Comment by franktoffel** [comment] 2024-12-15 19:50
Certainly, this line will not be used later.

`from ProcessOptimizer.learning import ExtraTreesRegressor`

**Comment by sqbl** [comment] 2024-12-15 20:30
Ahh, now I see :-)
We are looking into giving the samples/examples a bigger make-over, so we will look into this in due time. Meanwhile, (for the expert user), you can look in the new experimental XpyriMentor folder. This new feature will allow you to fully custom how your optimizer is to behave during an optimization.

@franktoffel, how would you feel for looking slightly deeper into this issue? Or perhaps to produce a new example to highlight the feature (changing length scale)? 
My initial believe for the reason of the newly observed behaviour is grounded in the "new" default distribution of initial points in a latin hyber cube structure - meaning that initial points are more evenly distributed. By shear "bad luck" this has distributed the five initial experiments so evenly above and below the average y-value. This would favour a high likelyhood for the model in which all signal is made by noise. You also see a very small model-uncertainty in the "new" second plot presented by franktoffel in support of this hypothesis. This leads us to some options/things to try: 
- disable latin-hyber-cube (lhs=False) in the optimizer, 
- add observational noise before plotting (opt.add_observational_noise()). this might give some indications for the modelled signal vs the modelled white-kernel noise (which is normally not plotted)
- likely something more which my brain will wake me up tonight to "discuss"

Again, thanks for bringing up this issue.

**Comment by sqbl** [comment] 2024-12-17 18:57
The issue should be solved by now. The observation from Franktoffel was correct and was an unexpected behavior. I have made minor changes in the example to avoid the evenly sampling of the initial points, which was the reason for the observed difference between the old example and the current behaviour of the package.
@franktoffel, I plan to close the issue with this comment. Feel free to reopen, start a new issue or PR an improved example.

**Closed as completed by sqbl** 2024-12-17 18:57 UTC
